export const seedCategories = [
  {
    name: "Women's Handbags",
    slug: "womens-handbags",
    gender: "WOMEN",
    description: "Sculptural leather silhouettes handcrafted by master Italian artisans.",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 1,
  },
  {
    name: "Women's Ready-to-Wear",
    slug: "womens-clothing",
    gender: "WOMEN",
    description: "Architectural tailoring, pure double-faced cashmere, and fluid silk forms.",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 2,
  },
  {
    name: "Women's Footwear",
    slug: "womens-shoes",
    gender: "WOMEN",
    description: "Clean geometric proportions in brushed calfskin and satin.",
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 3,
  },
  {
    name: "Fine Jewelry & Objects",
    slug: "jewelry-objects",
    gender: "UNISEX",
    description: "Solid sterling silver, raw hand-sculpted bronze, and natural baroque pearls.",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 4,
  },
  {
    name: "Men's Outerwear & Tailoring",
    slug: "mens-clothing",
    gender: "MEN",
    description: "Impeccable structural overcoats, raw wool blazers, and pure knitwear.",
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 5,
  },
  {
    name: "Men's Leather Goods",
    slug: "mens-bags",
    gender: "MEN",
    description: "Heavyweight full-grain leather briefcases, weekenders, and monolith totes.",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 6,
  },
  {
    name: "Men's Footwear",
    slug: "mens-shoes",
    gender: "MEN",
    description: "Blake-stitched Chelsea boots, Goodyear welted derbies, and raw leather loafers.",
    image: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=1000&auto=format&fit=crop",
    featured: true,
    order: 7,
  },
  {
    name: "Accessories & Silk",
    slug: "accessories-silk",
    gender: "UNISEX",
    description: "Mulberry silk foulards, raw leather belts, and cashmere scarves.",
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=1000&auto=format&fit=crop",
    featured: false,
    order: 8,
  },
];

export const seedCollections = [
  {
    name: "Autumn / Winter 2026",
    slug: "autumn-winter-2026",
    subtitle: "The Raw Architecture of Form",
    season: "AW 2026",
    description: "Explores the tension between monumental brutalist structure and the tender tactility of virgin cashmere and untamed leather.",
    bannerImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=2000&auto=format&fit=crop",
    featured: true,
  },
  {
    name: "Sculptural Monolith",
    slug: "sculptural-monolith",
    subtitle: "Pure Silhouette, Zero Clutter",
    season: "Permanent Collection",
    description: "An ongoing study in reduction. Heavyweight materials cut with uncompromising sharp lines.",
    bannerImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=2000&auto=format&fit=crop",
    featured: true,
  },
  {
    name: "Atelier Silk & Cashmere",
    slug: "atelier-silk-cashmere",
    subtitle: "Quiet Sensuality & Tactile Luxury",
    season: "Capsule",
    description: "Weightless 16-momme mulberry silks and grade-A Mongolian cashmere spun in Biella, Italy.",
    bannerImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=2000&auto=format&fit=crop",
    featured: true,
  },
  {
    name: "Equestrian Raw Leather",
    slug: "equestrian-raw-leather",
    subtitle: "Vegetable-Tanned Heritage Craft",
    season: "Permanent Collection",
    description: "Full-grain Tuscan saddle leathers hand-stitched with waxed linen thread.",
    bannerImage: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=2000&auto=format&fit=crop",
    featured: false,
  },
];

export const seedProducts = [
  // 1. Women's Handbag
  {
    name: "The Monolith Trapeze Bag",
    slug: "the-monolith-trapeze-bag",
    subtitle: "Architectural Calfskin Handbag",
    description: "Constructed with precision geometry, the Monolith Trapeze Bag exemplifies quiet architectural luxury. Sculpted from full-grain French calfskin with hand-lacquered edges and bespoke brushed brass hardware.",
    shortDescription: "Sculptural full-grain calfskin handbag with brushed palladium hardware.",
    price: 3450,
    compareAtPrice: null,
    sku: "LR-BAG-001",
    categorySlug: "womens-handbags",
    collectionSlug: "autumn-winter-2026",
    gender: "WOMEN",
    material: "100% Full-Grain French Calfskin, Nappa Leather Lining",
    careInstructions: "Avoid direct contact with water, perfume, and abrasive surfaces. Store in provided cotton dust bag.",
    origin: "Handcrafted in Florence, Italy",
    color: "Noir Obsidian",
    featured: true,
    newArrival: true,
    bestseller: true,
    variants: [
      { size: "Medium (32 x 22 x 14 cm)", color: "Noir Obsidian", colorHex: "#0a0a0a", stock: 8, sku: "LR-BAG-001-BLK-M" },
      { size: "Large (40 x 28 x 18 cm)", color: "Noir Obsidian", colorHex: "#0a0a0a", stock: 5, sku: "LR-BAG-001-BLK-L" },
      { size: "Medium (32 x 22 x 14 cm)", color: "Raw Umber", colorHex: "#4a3528", stock: 6, sku: "LR-BAG-001-UMB-M" },
      { size: "Medium (32 x 22 x 14 cm)", color: "Chalk Bone", colorHex: "#f0ede6", stock: 4, sku: "LR-BAG-001-CHK-M" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1200&auto=format&fit=crop", alt: "The Monolith Trapeze Bag in Noir Obsidian", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=1200&auto=format&fit=crop", alt: "Editorial side perspective of Monolith Bag", isPrimary: false, order: 2 },
      { url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1200&auto=format&fit=crop", alt: "Detail of brushed hardware and raw lacquered edges", isPrimary: false, order: 3 },
      { url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop", alt: "In-hand lifestyle presentation", isPrimary: false, order: 4 },
    ],
  },
  // 2. Women's Coat
  {
    name: "Sculpted Double-Faced Cashmere Coat",
    slug: "sculpted-double-faced-cashmere-coat",
    subtitle: "Floor-Length Maison Outerwear",
    description: "Meticulously woven in Biella from 100% Grade-A Mongolian cashmere. Features an unlined double-faced construction with invisible hand-finished seams, raglan sleeves, and a self-tie architectural belt.",
    shortDescription: "Hand-stitched pure cashmere floor-length coat with belted waist.",
    price: 4850,
    compareAtPrice: 5200,
    sku: "LR-CT-002",
    categorySlug: "womens-clothing",
    collectionSlug: "autumn-winter-2026",
    gender: "WOMEN",
    material: "100% Grade-A Double-Faced Cashmere",
    careInstructions: "Specialist luxury dry clean only. Store on shaped wooden hanger.",
    origin: "Tailored in Milan, Italy",
    color: "Raw Camel Stone",
    featured: true,
    newArrival: true,
    bestseller: false,
    variants: [
      { size: "IT 38 / US 2", color: "Raw Camel Stone", colorHex: "#c8b293", stock: 4, sku: "LR-CT-002-CAM-38" },
      { size: "IT 40 / US 4", color: "Raw Camel Stone", colorHex: "#c8b293", stock: 7, sku: "LR-CT-002-CAM-40" },
      { size: "IT 42 / US 6", color: "Raw Camel Stone", colorHex: "#c8b293", stock: 6, sku: "LR-CT-002-CAM-42" },
      { size: "IT 44 / US 8", color: "Raw Camel Stone", colorHex: "#c8b293", stock: 3, sku: "LR-CT-002-CAM-44" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=1200&auto=format&fit=crop", alt: "Sculpted Double-Faced Cashmere Coat full silhouette", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop", alt: "Close-up of lapel and double-faced hand stitching", isPrimary: false, order: 2 },
      { url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop", alt: "Editorial movement profile", isPrimary: false, order: 3 },
    ],
  },
  // 3. Women's Bag
  {
    name: "The Sculptural Arch Saddle Bag",
    slug: "the-sculptural-arch-saddle-bag",
    subtitle: "Vegetable-Tanned Saddle Leather",
    description: "An homage to modern sculpture. Curvature formed by cold-molding heavyweight bridle leather over hardwood casts, completed with an adjustable crossbody strap and magnetic closure.",
    shortDescription: "Cold-molded bridle leather saddle bag with magnetic flap closure.",
    price: 2600,
    compareAtPrice: null,
    sku: "LR-BAG-003",
    categorySlug: "womens-handbags",
    collectionSlug: "sculptural-monolith",
    gender: "WOMEN",
    material: "100% Vegetable-Tanned Saddle Calfskin",
    careInstructions: "Moisturize bi-annually with natural beeswax leather balsam.",
    origin: "Handcrafted in Florence, Italy",
    color: "Espresso Brut",
    featured: true,
    newArrival: false,
    bestseller: true,
    variants: [
      { size: "One Size (24 x 19 x 8 cm)", color: "Espresso Brut", colorHex: "#2b1c16", stock: 12, sku: "LR-BAG-003-ESP-OS" },
      { size: "One Size (24 x 19 x 8 cm)", color: "Matte Slate", colorHex: "#1c1c1c", stock: 9, sku: "LR-BAG-003-SLT-OS" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop", alt: "The Sculptural Arch Saddle Bag", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=1200&auto=format&fit=crop", alt: "Angle view of saddle silhouette", isPrimary: false, order: 2 },
    ],
  },
  // 4. Women's Tailored Blazer
  {
    name: "Architectural Virgin Wool Blazer",
    slug: "architectural-virgin-wool-blazer",
    subtitle: "Structured Single-Breasted Tailoring",
    description: "Sharply defined shoulders, suppressed waistline, and extended peak lapels create a commanding masculine-feminine balance. Woven from 100% high-twist tropical virgin wool.",
    shortDescription: "Structured peak-lapel blazer in high-twist virgin wool.",
    price: 2450,
    compareAtPrice: null,
    sku: "LR-JKT-004",
    categorySlug: "womens-clothing",
    collectionSlug: "sculptural-monolith",
    gender: "WOMEN",
    material: "100% Super 130s Virgin Wool, 100% Cupro Bemberg Lining",
    careInstructions: "Dry clean only. Steam press delicately.",
    origin: "Tailored in Naples, Italy",
    color: "Obsidian Black",
    featured: false,
    newArrival: true,
    bestseller: true,
    variants: [
      { size: "IT 38 / US 2", color: "Obsidian Black", colorHex: "#0d0d0d", stock: 5, sku: "LR-JKT-004-BLK-38" },
      { size: "IT 40 / US 4", color: "Obsidian Black", colorHex: "#0d0d0d", stock: 10, sku: "LR-JKT-004-BLK-40" },
      { size: "IT 42 / US 6", color: "Obsidian Black", colorHex: "#0d0d0d", stock: 8, sku: "LR-JKT-004-BLK-42" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop", alt: "Architectural Virgin Wool Blazer front", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop", alt: "Tailoring details and cuffs", isPrimary: false, order: 2 },
    ],
  },
  // 5. Women's Footwear
  {
    name: "The Sculptural Block Heel Mule",
    slug: "the-sculptural-block-heel-mule",
    subtitle: "Brushed Calfskin 75mm Mule",
    description: "A cantilevered geometric wood heel wrapped in polished black calfskin. Square chiseled toe with cushioned memory-foam leather footbed for effortless gallery-to-dinner comfort.",
    shortDescription: "Square-toe brushed calfskin mule with architectural 75mm heel.",
    price: 1150,
    compareAtPrice: null,
    sku: "LR-SH-005",
    categorySlug: "womens-shoes",
    collectionSlug: "sculptural-monolith",
    gender: "WOMEN",
    material: "100% Polished Italian Calfskin, Leather Sole with Rubber Inset",
    careInstructions: "Wipe clean with a soft dry cloth. Keep away from excessive moisture.",
    origin: "Handcrafted in Civitanova Marche, Italy",
    color: "Polished Nero",
    featured: true,
    newArrival: false,
    bestseller: false,
    variants: [
      { size: "EU 36 / US 6", color: "Polished Nero", colorHex: "#0a0a0a", stock: 4, sku: "LR-SH-005-BLK-36" },
      { size: "EU 37 / US 7", color: "Polished Nero", colorHex: "#0a0a0a", stock: 6, sku: "LR-SH-005-BLK-37" },
      { size: "EU 38 / US 8", color: "Polished Nero", colorHex: "#0a0a0a", stock: 8, sku: "LR-SH-005-BLK-38" },
      { size: "EU 39 / US 9", color: "Polished Nero", colorHex: "#0a0a0a", stock: 5, sku: "LR-SH-005-BLK-39" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1200&auto=format&fit=crop", alt: "The Sculptural Block Heel Mule", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?q=80&w=1200&auto=format&fit=crop", alt: "Heel architecture and leather sole detail", isPrimary: false, order: 2 },
    ],
  },
  // 6. Women's Dress
  {
    name: "Raw Pleated Crepe Column Gown",
    slug: "raw-pleated-crepe-column-gown",
    subtitle: "Floor-Length Artisanal Evening Dress",
    description: "Engineered with micro-plissé accordion pleating throughout the torso that unfurls gently toward the hemline. Open scoop back with minimalist silk cords.",
    shortDescription: "Floor-length micro-plissé evening gown in fluid heavy crepe.",
    price: 3200,
    compareAtPrice: null,
    sku: "LR-DR-006",
    categorySlug: "womens-clothing",
    collectionSlug: "atelier-silk-cashmere",
    gender: "WOMEN",
    material: "100% Silk Crepe de Chine",
    careInstructions: "Specialist dry clean only. Do not iron pleats.",
    origin: "Atelier Handcrafted in Como, Italy",
    color: "Ivory Alabaster",
    featured: true,
    newArrival: true,
    bestseller: false,
    variants: [
      { size: "IT 38 / US 2", color: "Ivory Alabaster", colorHex: "#f7f5f0", stock: 3, sku: "LR-DR-006-IVO-38" },
      { size: "IT 40 / US 4", color: "Ivory Alabaster", colorHex: "#f7f5f0", stock: 5, sku: "LR-DR-006-IVO-40" },
      { size: "IT 42 / US 6", color: "Ivory Alabaster", colorHex: "#f7f5f0", stock: 4, sku: "LR-DR-006-IVO-42" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=1200&auto=format&fit=crop", alt: "Raw Pleated Crepe Column Gown full length", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1200&auto=format&fit=crop", alt: "Back silhouette and movement", isPrimary: false, order: 2 },
    ],
  },
  // 7. Women's Jewelry
  {
    name: "The Monolith Hand-Carved Bronze Cuff",
    slug: "the-monolith-hand-carved-bronze-cuff",
    subtitle: "Heavyweight Cast Sculpture Cuff",
    description: "Cast using the ancient lost-wax process and hand-chiseled to preserve organic textural imperfections. Finished with a satin 18k yellow gold vermeil plating.",
    shortDescription: "Lost-wax cast architectural cuff in 18k gold vermeil over solid bronze.",
    price: 980,
    compareAtPrice: null,
    sku: "LR-JWL-007",
    categorySlug: "jewelry-objects",
    collectionSlug: "sculptural-monolith",
    gender: "UNISEX",
    material: "Solid Bronze with 5-Micron 18K Yellow Gold Vermeil",
    careInstructions: "Wipe with microfiber jewelers cloth. Keep free from cosmetics.",
    origin: "Handcrafted in Arezzo, Italy",
    color: "Brushed Aureum",
    featured: true,
    newArrival: false,
    bestseller: true,
    variants: [
      { size: "Small / Medium (16 cm)", color: "Brushed Aureum", colorHex: "#d4af37", stock: 15, sku: "LR-JWL-007-SM" },
      { size: "Medium / Large (18.5 cm)", color: "Brushed Aureum", colorHex: "#d4af37", stock: 11, sku: "LR-JWL-007-ML" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop", alt: "The Monolith Hand-Carved Bronze Cuff", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1611591475155-4286fa292e7a?q=80&w=1200&auto=format&fit=crop", alt: "Wrist presentation and textural close up", isPrimary: false, order: 2 },
    ],
  },
  // 8. Women's Silk Scarf
  {
    name: "The Raw Geometry Mulberry Silk Foulard",
    slug: "the-raw-geometry-mulberry-silk-foulard",
    subtitle: "90 x 90 cm Hand-Rolled Silk Twill",
    description: "Printed on heavy 18-momme mulberry silk twill with an original architectural monograph. Edges are hand-rolled and hand-sewn by master silk artisans in Como.",
    shortDescription: "Hand-rolled heavy silk twill foulard with monochromatic geometric artwork.",
    price: 495,
    compareAtPrice: null,
    sku: "LR-ACC-008",
    categorySlug: "accessories-silk",
    collectionSlug: "autumn-winter-2026",
    gender: "UNISEX",
    material: "100% Mulberry Silk Twill (18-Momme)",
    careInstructions: "Dry clean only. Cool iron on reverse.",
    origin: "Printed and Rolled in Como, Italy",
    color: "Monochrome Charcoal & Ecru",
    featured: false,
    newArrival: true,
    bestseller: false,
    variants: [
      { size: "90 x 90 cm", color: "Monochrome Charcoal", colorHex: "#333333", stock: 20, sku: "LR-ACC-008-OS" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?q=80&w=1200&auto=format&fit=crop", alt: "The Raw Geometry Mulberry Silk Foulard", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1200&auto=format&fit=crop", alt: "Foulard tied around bag handle", isPrimary: false, order: 2 },
    ],
  },
  // 9. Men's Overcoat
  {
    name: "The Monumental Raw Wool Greatcoat",
    slug: "the-monumental-raw-wool-greatcoat",
    subtitle: "Heavyweight Double-Breasted Winter Coat",
    description: "Engineered from 950g virgin melton wool sourced from the Scottish borders. Features an elongated broad lapel, horn buttons, deep internal storm pockets, and a dramatic back vent.",
    shortDescription: "950g Scottish virgin melton wool double-breasted greatcoat.",
    price: 4400,
    compareAtPrice: null,
    sku: "LR-MCT-009",
    categorySlug: "mens-clothing",
    collectionSlug: "autumn-winter-2026",
    gender: "MEN",
    material: "100% Heavy Virgin Melton Wool, Bemberg Cupro Lining",
    careInstructions: "Specialist wool dry clean only. Store on wide cedar hanger.",
    origin: "Tailored in Biella, Italy",
    color: "Deep Ink Obsidian",
    featured: true,
    newArrival: true,
    bestseller: true,
    variants: [
      { size: "EU 48 / US 38", color: "Deep Ink Obsidian", colorHex: "#0b0c10", stock: 4, sku: "LR-MCT-009-INK-48" },
      { size: "EU 50 / US 40", color: "Deep Ink Obsidian", colorHex: "#0b0c10", stock: 8, sku: "LR-MCT-009-INK-50" },
      { size: "EU 52 / US 42", color: "Deep Ink Obsidian", colorHex: "#0b0c10", stock: 6, sku: "LR-MCT-009-INK-52" },
      { size: "EU 54 / US 44", color: "Deep Ink Obsidian", colorHex: "#0b0c10", stock: 3, sku: "LR-MCT-009-INK-54" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop", alt: "The Monumental Raw Wool Greatcoat full silhouette", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=1200&auto=format&fit=crop", alt: "Double-breasted lapel and horn button detailing", isPrimary: false, order: 2 },
      { url: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop", alt: "Street editorial perspective", isPrimary: false, order: 3 },
    ],
  },
  // 10. Men's Leather Bag
  {
    name: "The Atelier 48-Hour Raw Leather Duffle",
    slug: "the-atelier-48-hour-raw-leather-duffle",
    subtitle: "Full-Grain Saddle Leather Weekender",
    description: "Constructed with uncompromised integrity from 3.2mm full-grain vegetable-tanned bridle leather. Hand-stitched rolled handles, solid brass Raccagni hardware, and a reinforced bottom panel with protective brass studs.",
    shortDescription: "Full-grain vegetable-tanned bridle leather 48-hour travel bag.",
    price: 3850,
    compareAtPrice: null,
    sku: "LR-MBAG-010",
    categorySlug: "mens-bags",
    collectionSlug: "equestrian-raw-leather",
    gender: "MEN",
    material: "100% Full-Grain Vegetable-Tanned Tuscan Leather, Heavy Cotton Twill Lining",
    careInstructions: "Condition every 6 months with natural leather oil. Embraces natural patina over time.",
    origin: "Handcrafted in Florence, Italy",
    color: "Raw Tuscan Havana",
    featured: true,
    newArrival: false,
    bestseller: true,
    variants: [
      { size: "52 x 30 x 26 cm (45L)", color: "Raw Tuscan Havana", colorHex: "#3e2723", stock: 7, sku: "LR-MBAG-010-HAV-OS" },
      { size: "52 x 30 x 26 cm (45L)", color: "Matte Pitch Black", colorHex: "#111111", stock: 9, sku: "LR-MBAG-010-BLK-OS" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1200&auto=format&fit=crop", alt: "The Atelier 48-Hour Raw Leather Duffle", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop", alt: "Leather grain and brass hardware detail", isPrimary: false, order: 2 },
    ],
  },
  // 11. Men's Knitwear
  {
    name: "Architectural Gauge-3 Cashmere Turtleneck",
    slug: "architectural-gauge-3-cashmere-turtleneck",
    subtitle: "Heavyweight 6-Ply Ribbed Knit",
    description: "Knit on traditional flatbed looms from 6-ply Mongolian cashmere. Features an imposing architectural funnel neck, raglan armholes, and dense gauge-3 cardigan ribbing that holds its sculpture indefinitely.",
    shortDescription: "Dense 6-ply pure cashmere gauge-3 ribbed funnel turtleneck.",
    price: 1950,
    compareAtPrice: null,
    sku: "LR-KNT-011",
    categorySlug: "mens-clothing",
    collectionSlug: "atelier-silk-cashmere",
    gender: "MEN",
    material: "100% Pure Mongolian Cashmere (6-Ply, Gauge-3)",
    careInstructions: "Hand wash in cool water with gentle cashmere shampoo. Dry flat on towels.",
    origin: "Spun & Knitted in Umbria, Italy",
    color: "Oatmeal Melange",
    featured: true,
    newArrival: true,
    bestseller: false,
    variants: [
      { size: "Small (EU 46)", color: "Oatmeal Melange", colorHex: "#ded7cc", stock: 5, sku: "LR-KNT-011-OAT-S" },
      { size: "Medium (EU 48)", color: "Oatmeal Melange", colorHex: "#ded7cc", stock: 8, sku: "LR-KNT-011-OAT-M" },
      { size: "Large (EU 50)", color: "Oatmeal Melange", colorHex: "#ded7cc", stock: 9, sku: "LR-KNT-011-OAT-L" },
      { size: "X-Large (EU 52)", color: "Oatmeal Melange", colorHex: "#ded7cc", stock: 4, sku: "LR-KNT-011-OAT-XL" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=1200&auto=format&fit=crop", alt: "Architectural Gauge-3 Cashmere Turtleneck", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop", alt: "Funnel neck texture and ribbed stitch detail", isPrimary: false, order: 2 },
    ],
  },
  // 12. Men's Boots
  {
    name: "The Raw Chiseled-Toe Chelsea Boot",
    slug: "the-raw-chiseled-toe-chelsea-boot",
    subtitle: "Goodyear-Welted French Boxcalf Boot",
    description: "An elongated chiseled square toe with bevelled waist and concealed tonal elastic gussets. Constructed using traditional 270-degree Goodyear welt technique on natural stacked leather heels.",
    shortDescription: "Goodyear-welted boxcalf Chelsea boot with chiseled toe.",
    price: 1350,
    compareAtPrice: null,
    sku: "LR-MSH-012",
    categorySlug: "mens-shoes",
    collectionSlug: "sculptural-monolith",
    gender: "MEN",
    material: "100% French Full-Grain Boxcalf, Oak-Bark Tanned Leather Sole",
    careInstructions: "Polish with natural carnauba wax cream. Always insert cedar shoe trees after wear.",
    origin: "Handcrafted in Northamptonshire, England",
    color: "Aniline Noir",
    featured: false,
    newArrival: true,
    bestseller: true,
    variants: [
      { size: "EU 41 / US 8", color: "Aniline Noir", colorHex: "#090909", stock: 4, sku: "LR-MSH-012-BLK-41" },
      { size: "EU 42 / US 9", color: "Aniline Noir", colorHex: "#090909", stock: 7, sku: "LR-MSH-012-BLK-42" },
      { size: "EU 43 / US 10", color: "Aniline Noir", colorHex: "#090909", stock: 8, sku: "LR-MSH-012-BLK-43" },
      { size: "EU 44 / US 11", color: "Aniline Noir", colorHex: "#090909", stock: 5, sku: "LR-MSH-012-BLK-44" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1614252369475-531eba835eb1?q=80&w=1200&auto=format&fit=crop", alt: "The Raw Chiseled-Toe Chelsea Boot pair", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=1200&auto=format&fit=crop", alt: "Profile view and leather sole welt", isPrimary: false, order: 2 },
    ],
  },
  // 13. Men's Leather Briefcase
  {
    name: "The Monolith Architectural Briefcase",
    slug: "the-monolith-architectural-briefcase",
    subtitle: "Structured Hard-Frame Document Case",
    description: "Engineered around a lightweight aluminum internal armature covered in museum-grade calfskin. Concealed push-lock mechanism with custom engraved key.",
    shortDescription: "Architectural structured briefcase in museum calfskin with lock closure.",
    price: 3600,
    compareAtPrice: null,
    sku: "LR-MBAG-013",
    categorySlug: "mens-bags",
    collectionSlug: "sculptural-monolith",
    gender: "MEN",
    material: "100% Hand-Dyed Museum Calfskin, Suede Microfiber Lining",
    careInstructions: "Store in protective felt sleeve when not in use.",
    origin: "Handcrafted in Florence, Italy",
    color: "Charcoal Slate",
    featured: true,
    newArrival: false,
    bestseller: false,
    variants: [
      { size: "39 x 29 x 7 cm", color: "Charcoal Slate", colorHex: "#262626", stock: 6, sku: "LR-MBAG-013-CHR-OS" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1200&auto=format&fit=crop", alt: "The Monolith Architectural Briefcase", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop", alt: "Lock mechanism and handle structure", isPrimary: false, order: 2 },
    ],
  },
  // 14. Men's Ring
  {
    name: "The Solid Sterling Monolith Signet",
    slug: "the-solid-sterling-monolith-signet",
    subtitle: "Heavyweight 925 Sterling Silver Ring",
    description: "Solid 925 sterling silver with a stepped geometric silhouette inspired by brutalist architecture. Hand-finished with a brushed matte top surface and high-polished bevels.",
    shortDescription: "Solid 925 sterling silver signet ring with stepped geometric bezel.",
    price: 650,
    compareAtPrice: null,
    sku: "LR-JWL-014",
    categorySlug: "jewelry-objects",
    collectionSlug: "sculptural-monolith",
    gender: "UNISEX",
    material: "Solid 925 Sterling Silver (28 Grams)",
    careInstructions: "Clean with silver polishing cloth. Avoid sulfur and chlorine pools.",
    origin: "Cast & Hand-Finished in Valenza, Italy",
    color: "Brushed Argento",
    featured: false,
    newArrival: true,
    bestseller: true,
    variants: [
      { size: "US 8 / EU 57", color: "Brushed Argento", colorHex: "#cccccc", stock: 10, sku: "LR-JWL-014-8" },
      { size: "US 9 / EU 60", color: "Brushed Argento", colorHex: "#cccccc", stock: 12, sku: "LR-JWL-014-9" },
      { size: "US 10 / EU 62", color: "Brushed Argento", colorHex: "#cccccc", stock: 11, sku: "LR-JWL-014-10" },
      { size: "US 11 / EU 65", color: "Brushed Argento", colorHex: "#cccccc", stock: 7, sku: "LR-JWL-014-11" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1611591475155-4286fa292e7a?q=80&w=1200&auto=format&fit=crop", alt: "The Solid Sterling Monolith Signet Ring", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop", alt: "Bezel facet and side profile", isPrimary: false, order: 2 },
    ],
  },
  // 15. Women's Evening Bag
  {
    name: "The Raw Cast Metal Minaudière",
    slug: "the-raw-cast-metal-minaudiere",
    subtitle: "Solid Cast Brass Evening Clutch",
    description: "A wearable objet d'art. Sculpted from molten brass with a tactile hammered finish, lined in midnight lambskin nappa. Features a detachable faceted curb chain strap.",
    shortDescription: "Cast brass sculptural evening clutch with lambskin lining.",
    price: 2950,
    compareAtPrice: null,
    sku: "LR-BAG-015",
    categorySlug: "womens-handbags",
    collectionSlug: "sculptural-monolith",
    gender: "WOMEN",
    material: "100% Cast Brass with Palladium Flash, 100% Italian Lambskin Lining",
    careInstructions: "Handle with jewelry gloves or clean microfiber cloth.",
    origin: "Crafted in Milan, Italy",
    color: "Polished Palladium",
    featured: true,
    newArrival: true,
    bestseller: false,
    variants: [
      { size: "18 x 11 x 6 cm", color: "Polished Palladium", colorHex: "#e0e0e0", stock: 6, sku: "LR-BAG-015-PAL-OS" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=1200&auto=format&fit=crop", alt: "The Raw Cast Metal Minaudière", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1200&auto=format&fit=crop", alt: "Metallic sculpture surface texture", isPrimary: false, order: 2 },
    ],
  },
  // 16. Men's Tailored Trousers
  {
    name: "Raw Wool Pleated Wide-Leg Trousers",
    slug: "raw-wool-pleated-wide-leg-trousers",
    subtitle: "High-Rise Double Forward Pleat",
    description: "Tailored with a generous fluid drape from heavy 420g English wool flannel. Features a 4cm extended waistband, side adjusters, and deep forward double pleats.",
    shortDescription: "High-rise double pleat tailored wide trousers in 420g wool flannel.",
    price: 1250,
    compareAtPrice: null,
    sku: "LR-TR-016",
    categorySlug: "mens-clothing",
    collectionSlug: "autumn-winter-2026",
    gender: "MEN",
    material: "100% English Wool Flannel, Horn Buttons",
    careInstructions: "Dry clean only. Press with damp cloth.",
    origin: "Tailored in Naples, Italy",
    color: "Graphite Melange",
    featured: false,
    newArrival: false,
    bestseller: true,
    variants: [
      { size: "IT 46 / US 30", color: "Graphite Melange", colorHex: "#474747", stock: 5, sku: "LR-TR-016-GRP-46" },
      { size: "IT 48 / US 32", color: "Graphite Melange", colorHex: "#474747", stock: 9, sku: "LR-TR-016-GRP-48" },
      { size: "IT 50 / US 34", color: "Graphite Melange", colorHex: "#474747", stock: 8, sku: "LR-TR-016-GRP-50" },
      { size: "IT 52 / US 36", color: "Graphite Melange", colorHex: "#474747", stock: 4, sku: "LR-TR-016-GRP-52" },
    ],
    images: [
      { url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop", alt: "Raw Wool Pleated Wide-Leg Trousers full drape", isPrimary: true, order: 1 },
      { url: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?q=80&w=1200&auto=format&fit=crop", alt: "Waistband adjusters and pleat structure", isPrimary: false, order: 2 },
    ],
  },
];

export const seedStores = [
  {
    name: "Maison luxury.Raw Paris Flagship",
    city: "Paris",
    country: "France",
    address: "24 Place Vendôme / Rue Saint-Honoré",
    postalCode: "75001",
    phone: "+33 1 42 68 00 24",
    email: "vendome@luxuryraw.com",
    hours: "Monday – Saturday: 10:00 – 19:30 | Sunday: By Private Appointment",
    services: "Private Salon Appointments, Made-to-Measure Tailoring, Bespoke Leather Monogramming, Champagne Concierge, In-Store Atelier Repairs",
    latitude: 48.8675,
    longitude: 2.3294,
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1200&auto=format&fit=crop",
    isFlagship: true,
  },
  {
    name: "luxury.Raw Milan Quadrilatero",
    city: "Milan",
    country: "Italy",
    address: "Via Montenapoleone 18",
    postalCode: "20121",
    phone: "+39 02 7600 1818",
    email: "montenapoleone@luxuryraw.com",
    hours: "Monday – Saturday: 10:00 – 19:30 | Sunday: 11:00 – 19:00",
    services: "Master Tailor Residency, Leather Care Clinic, VIP Rooftop Terrace, Personal Styling Concierge",
    latitude: 45.4697,
    longitude: 9.1956,
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1200&auto=format&fit=crop",
    isFlagship: true,
  },
  {
    name: "luxury.Raw New York Madison",
    city: "New York",
    country: "United States",
    address: "714 Madison Avenue (at 63rd Street)",
    postalCode: "10065",
    phone: "+1 212 555 0192",
    email: "madison@luxuryraw.com",
    hours: "Monday – Saturday: 10:00 – 19:00 | Sunday: 12:00 – 18:00",
    services: "Private Client Suites, Same-Day Manhattan White-Glove Delivery, Archive Collection Gallery",
    latitude: 40.7658,
    longitude: -73.9702,
    image: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1200&auto=format&fit=crop",
    isFlagship: true,
  },
  {
    name: "luxury.Raw Tokyo Ginza Maison",
    city: "Tokyo",
    country: "Japan",
    address: "6-10-1 Ginza, Chuo-ku",
    postalCode: "104-0061",
    phone: "+81 3 5555 0184",
    email: "ginza@luxuryraw.com",
    hours: "Monday – Sunday: 11:00 – 20:00",
    services: "Tea Room & Private Viewing Suite, Artisan Leather Workshop, Special Orders Atelier",
    latitude: 35.6696,
    longitude: 139.7645,
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1200&auto=format&fit=crop",
    isFlagship: true,
  },
  {
    name: "luxury.Raw London Mayfair",
    city: "London",
    country: "United Kingdom",
    address: "142 New Bond Street",
    postalCode: "W1S 2TL",
    phone: "+44 20 7499 0014",
    email: "newbond@luxuryraw.com",
    hours: "Monday – Saturday: 10:00 – 19:00 | Sunday: 12:00 – 18:00",
    services: "Mayfair Private Salon, Made-to-Measure Greatcoat Service, Bespoke Gift Curation",
    latitude: 51.5126,
    longitude: -0.1444,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop",
    isFlagship: true,
  },
];

export const seedEditorials = [
  {
    slug: "the-art-of-raw-craftsmanship",
    title: "The Raw Geometry of Form: An Atelier Chronicle",
    subtitle: "Inside our Tuscan leather workshops where monumental form meets untamed precision.",
    excerpt: "True luxury is the absence of unnecessary ornament. In our Florentine ateliers, raw saddlery techniques from the nineteenth century are reborn through brutalist architectural silhouettes.",
    content: `
# The Architecture of Modern Luxury

In a culture dominated by ephemeral novelty and loud logos, **luxury.Raw** seeks the quiet resonance of raw material truth. 

Every silhouette in our Autumn/Winter 2026 collection begins not with a sketch of surface embellishment, but with an architectural problem: *How does pure volume intersect the human body?*

### The Tuscan Tannery Tradition
Nestled along the banks of the Arno River, our partner tanners have practiced slow vegetable tanning for five generations. Using only natural chestnut bark tannins, untreated river water, and tallow oils, each hide matures inside oak vats for up to sixty days. 

The resulting leather retains its organic grain variations, insect marks, and subtle tonal shifts. It is not painted over or corrected with plastic polyurethanes. It breathes. It patinas. It tells a lifetime of stories.

> "A piece from luxury.Raw is not finished when it leaves our hands in Florence; it only truly begins when the wearer imprints their life into its grain."
> — *Gianluigi Rossi, Master Atelier Craftsman*

### The Monolith Trapeze Philosophy
Take, for example, the **Monolith Trapeze Bag**. Its structural integrity relies on the tension of cold-molded 3.2mm bridle calfskin. Each seam is hand-punched and saddle-stitched with waxed linen thread—a technique virtually unchanged since the saddle-makers of the Italian Renaissance.

When viewed from the front, the bag presents a pure, sharp isosceles geometry. From the side, its generous gussets reveal an organic depth that expands to accommodate the essentials of the modern nomad.

### Looking Toward Permanent Quality
In our vision of luxury, permanence is the ultimate rebellion. By focusing on monolithic form, virgin natural fibers, and unhurried artisanal production, luxury.Raw establishes a relationship of enduring intimacy between the object and the wearer.
    `,
    heroImage: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1000&auto=format&fit=crop",
    author: "Maison luxury.Raw Atelier",
    readTime: "5 min read",
    category: "Artisanship",
    featured: true,
    tags: "Craftsmanship, Leather, Florence, Architecture, AW26",
  },
  {
    slug: "monumental-wool-and-biella-cashmere",
    title: "Tactile Monoliths: The Alchemy of Biella Cashmere",
    subtitle: "Tracing our virgin double-faced wools from Alpine spring waters to Milanese cutting tables.",
    excerpt: "Discover the heritage mills of Piedmont where glacial waters finish the world's most sumptuous double-faced cashmere Greatcoats.",
    content: `
# Where Glacial Water Meets Pure Fiber

At the foothills of the Italian Alps, the town of Biella possesses a geological secret: water with almost zero mineral hardness. This exceptional purity allows virgin cashmere fibers to bloom to their fullest softness during the washing and teaseling processes.

### Double-Faced Mastery
Our signature **Sculpted Double-Faced Cashmere Coat** features an unlined construction that requires supreme sartorial prowess. Two layers of pure Grade-A cashmere are woven together on the loom with microscopic connecting threads. 

At our Milanese workshop, tailors carefully slit the edges by hand, fold each raw margin inward by 4 millimeters, and blind-stitch them with invisible silk threads. A single coat requires over twelve hours of hand-stitching alone.

### The Weight of Silence
There is an unmistakable quietness in wearing tailored garments that carry substance without stiffness. The coat flows with the stride yet retains a razor-sharp shoulder line that commands any room.
    `,
    heroImage: "https://images.unsplash.com/photo-1445205170230-053b83016050?q=80&w=1800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=1000&auto=format&fit=crop",
    author: "Elena Vasari, Textile Curator",
    readTime: "4 min read",
    category: "Materials",
    featured: true,
    tags: "Cashmere, Biella, Tailoring, Outerwear",
  },
  {
    slug: "lost-wax-jewelry-in-arezzo",
    title: "Sculpting Raw Light: Lost-Wax Bronze & Solid Silver",
    subtitle: "The ancient goldsmithing techniques behind our sculptural cuffs and signet monoliths.",
    excerpt: "Exploring the tactile imperfections and hand-chiseled surfaces of the luxury.Raw jewelry capsule.",
    content: `
# Lost-Wax Casting & Modern Brutalism

Before metal meets skin, it exists as hand-carved jeweler's wax. In Arezzo—the historic epicenter of Tuscan metallurgy—our master jewelers sculpt each piece individually.

### The Beauty of the Raw Margin
Unlike mass-produced, machine-polished jewelry, luxury.Raw embraces the organic micro-textures left by the sculptor’s chisels and the heat of molten bronze.

Each cuff is cast using the 5,000-year-old lost-wax technique (*cera persa*), hand-filed, and layered with a generous 5-micron coat of 18-karat yellow gold vermeil or dipped in liquid palladium.

The result is wearable sculpture: heavy in the palm, cool against the skin, and unmistakably distinct.
    `,
    heroImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1611591475155-4286fa292e7a?q=80&w=1000&auto=format&fit=crop",
    author: "Marcello Renzi",
    readTime: "3 min read",
    category: "Culture",
    featured: false,
    tags: "Jewelry, Lost-Wax, Gold, Silver, Arezzo",
  },
  {
    slug: "the-monochrome-wardrobe-philosophy",
    title: "The Monochromatic Wardrobe: A Manifesto of Restraint",
    subtitle: "Why limiting the palette unlocks exponential expressive power.",
    excerpt: "An exploration into why obsidian, chalk bone, raw camel, and slate form the eternal foundation of modern style.",
    content: `
# The Discipline of Reduction

When color is distilled to its fundamental tonal frequencies—deep ink obsidian, warm alabaster, raw umber, and weathered stone—the eye is liberated to perceive what truly matters: texture, proportion, drape, and silhouette.

A monochrome wardrobe is not about absence; it is about profound presence. When you strip away distracting pattern and loud branding, what remains is the pure character of the individual and the supreme quality of the garment.
    `,
    heroImage: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1800&auto=format&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1000&auto=format&fit=crop",
    author: "Maison Editorial Board",
    readTime: "4 min read",
    category: "Runway",
    featured: false,
    tags: "Monochrome, Philosophy, Minimalist, Wardrobe",
  },
];

export const seedCoupons = [
  {
    code: "MAISON10",
    description: "Privileged 10% Maison Welcome Courtesies",
    discountType: "PERCENTAGE",
    discountValue: 10,
    minOrderValue: 500,
    isActive: true,
  },
  {
    code: "RAWVIP20",
    description: "Exclusive 20% Private Client Salon Privileges",
    discountType: "PERCENTAGE",
    discountValue: 20,
    minOrderValue: 2000,
    isActive: true,
  },
  {
    code: "WELCOME100",
    description: "$100 Complimentary Maison Privilege on First Acquisition",
    discountType: "FIXED",
    discountValue: 100,
    minOrderValue: 1000,
    isActive: true,
  },
];
